server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/user-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: prakarsh2101@gmail.com
    password: pkpuigkgyvjrzpta
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
